I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/quiz.rpy", line 514, in script
    "[error_message[-1]]"
TypeError: list indices must be integers or slices, not str

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/quiz.rpy", line 514, in script
    "[error_message[-1]]"
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.1.3-sdk\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\renpy-8.1.3-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\renpy-8.1.3-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\renpy-8.1.3-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "D:\renpy-8.1.3-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 278, in get_field
  File "D:\renpy-8.1.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
TypeError: list indices must be integers or slices, not str

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Kodigo 1.0
Sun Mar 24 20:12:23 2024
